name = "Deer Diary"
author = "ToxicBananaParty"
version = "2026.05.31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5eaa094af8c40ae6a6bffa51f8088b5d48ec4eb11cc23ef3857ee3c772ee143"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
