name = "Deer Diary"
author = "ToxicBananaParty"
version = "2026.05.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee48f91e612f6a7238857eb1cea6dd6b82aaa0fe6cb0e280d0aee51dd16abd2b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
